# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoSwiftFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwiftFramework

  target 'DemoSwiftFrameworkTests' do
    # Pods for testing
  end

end
